---
apiVersion: v1
kind: Pod
metadata:
        name: team39-pod
        labels:
                app: team39-pod
spec:
    containers:
      - name: rest-server
        image: sarawill86/restserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      - name: frontend
        image: sarawill86/frontend:latest
        imagePullPolicy: Always
        command: ["npm", "start"]
        ports:
        - containerPort: 3000  
            
---
apiVersion: v1
kind: Service
metadata:
        name: website
        labels:
                app: website
spec:
        type: NodePort
        selector:
                app: team39-pod
        ports:
                - name: http
                  protocol: TCP
                  targetPort: 3000
                  port: 80
                  nodePort: 30001
