---
apiVersion: v1
kind: Pod
metadata:
    name: team39-pod
    labels:
        app: team39-pod
spec:
    containers:
        name: rest-server
        image: projectserver:latest
        imagePullPolicy: Always
        ports:
            containerPort: 8080
            
---
apiVersion: v1
kind: Service
metadata:
    name: rest-service
    labels:
        app: rest-service
spec:
    type: NodePort
    selector:
        app: team39-pod
    ports:
        name: http
        protocol: TCP
        targetPort: 8080
        port: 80
        nodePort: 30001
